<h2>Klan - Opprett Klan</h2>

<?php

$form = $this->form;
$form->setAttribute('action', $this->url(
		'guild', array(
			'action' => 'create'
		)
));
$form->prepare();

echo $this->form()->openTag($form) . "\n";
echo $this->formRow($form->get('name')) . "\n";
echo $this->formRow($form->get('description')) . "\n";
echo $this->formRow($form->get('submit')) . "\n";
echo $this->form()->closeTag($form);

?>

<br><a href='<?php echo $this->url('guild'); ?>'>Tilbake</a>