<h2>Klan - Inviter spiller til klan: <?php echo $this->guildInfo->name; ?></h2>

<?php

$form = $this->form;
$form->setAttribute('action', $this->url('guild', array(
		'action' => 'invite',
		'id' => $this->guildInfo->guildID
	)
));
$form->prepare();

echo $this->form()->openTag($form) . "\n";
echo $this->formRow($form->get('username')) . "\n";
echo $this->formRow($form->get('message')) . "\n";
echo $this->formRow($form->get('submit')) . "\n";
echo $this->form()->closeTag($form);

?>

<br><a href='<?php echo $this->url('guild'); ?>'>Tilbake</a>