<h2>Jernsmelteverk</h2>

<?php

// Print eventual message
if($this->message) {
	echo "<div class='message'>" . $this->message . "</div>";
}


if($this->townHasStorage) {

?>

<h4>Resurser i landsbyen</h4>
Jernmalm: <?php echo $this->townNrOfIronOre; ?><br>
Jern: <?php echo $this->townNrOfIron; ?>

<?php

}

?>

<h4>Resurser i din inventar</h4>
Jernmalm: <?php echo $this->nrOfIronOre; ?><br>
Jern: <?php echo $this->nrOfIron; ?>

<h3>Smelt jernmalm</h3>

<?php

$meltFormAction = $this->url('town', array(
		'controller' => 'iron-melting-works',
		'action' => 'melt',
		'longitude' => $this->longitude,
		'latitude' => $this->latitude
));

if($this->townHasStorage) {
	echo "<h4>Fra landsbyen</h4>";
	
	if($this->townNrOfIronOre > 0) {

?>

<form action='<?php echo $meltFormAction; ?>' method='POST'>
<input type='hidden' name='resourceContainer' value='storage'>
<input type='submit' value='Smelt jernmalm'>
</form>

<?php

	} else {
		echo "Det finnes ikke noe jernmalm i landsbyen som kan smeltes.";
	}
}


if($this->nrOfIronOre > 0) {

?>

<h4>Fra din inventar</h4>

<form action='<?php echo $meltFormAction; ?>' method='POST'>
<input type='hidden' name='resourceContainer' value='inventory'>
<input type='submit' value='Smelt jernmalm'>
</form>

<?php

} else {
	echo "Du har ikke noe jernmalm i din inventar som kan smeltes.";
}


$backUrl = $this->url('town', array(
	'longitude' => $this->longitude,
	'latitude' => $this->latitude
));

?>

<br><br><a href='<?php echo $backUrl; ?>'>Tilbake til landsby</a>