<div id="forestSquareContainer">
<div class="form">

<?php

if(!$this->blocked) {
	$url = $this->url('game', array(
		'controller' => 'mapsquare',
		'action' => 'index'
	));

?>

<form action="<?php echo $url; ?>" method="POST">
	<input type="hidden" name="squareAction" value="forest">
	<input type="submit" id="submit" name="submit" value="Hugg tre">
</form>

<?php

} else {
	echo $this->message;
}

?>

</div>
</div>