<?php echo $this->doctype(); ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 '. $this->translate('Age of Vikings'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                    ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                    ->prependStylesheet($this->basePath() . '/css/style.css')
                    ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
    				->prependStylesheet($this->basePath() . '/css/site.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                  ->prependFile($this->basePath() . '/js/jquery-1.7.2.min.js') ?>

  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php echo $this->url('home') ?>">Age of Vikings</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="<?php echo $this->url('application', array('controller' => 'auth')); ?>"><?php echo $this->translate('Logg inn'); ?></a></li>
              <li class="active"><a href="<?php echo $this->url('game'); ?>"><?php echo $this->translate('Map'); ?></a></li>
              <li class="active"><a href="<?php echo $this->url('game', array('controller' => 'inventory')); ?>"><?php echo $this->translate('Inventory'); ?></a></li>
              <li class="active"><a href="<?php echo $this->url('town'); ?>"><?php echo $this->translate('Town'); ?></a></li>
              <li class="active"><a href="<?php echo $this->url('game', array('controller' => 'quest')); ?>"><?php echo $this->translate('Quest'); ?></a></li>
              <li class="active"><a href="<?php echo $this->url('message'); ?>"><?php echo $this->translate('Mail'); ?></a></li>
              <li class="active"><a href="<?php echo $this->url('guild'); ?>"><?php echo $this->translate('Guild'); ?></a></li>
              <li class="active"><a href="<?php echo $this->url('application', array('controller' => 'auth', 'action' => 'logout')); ?>"><?php echo $this->translate('Logg ut'); ?></a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      <?php echo $this->content; ?>

      <hr>

      <footer>
        <p>&copy; 2012 by Bjerkerud Software <?php echo $this->translate('All rights reserved.') ?></p>
      </footer>

    </div> <!-- /container -->

  <?php echo $this->inlineScript() ?>
  </body>
</html>
