<h2>Sagebukk</h2>

<?php

// Print eventual message
if($this->message) {
	echo "<div class='message'>" . $this->message . "</div>";
}

?>

Tømmerstokker: <?php echo $this->nrOfLog; ?><br>
Plank: <?php echo $this->nrOfLumber; ?>

<h3>Skjær tømmer</h3>

<?php

if($this->nrOfLog > 0) {
	$cutFormAction = $this->url('town', array(
		'controller' => 'saw-buck',
		'action' => 'cut',
		'longitude' => $this->longitude,
		'latitude' => $this->latitude
	));

?>

<form action='<?php echo $cutFormAction; ?>' method='POST'>
<input type='submit' value='Skjær tømmer'>
</form>

<?php

} else {
	echo "Du har ingen tømmerstokker i din inventar som kan sages.";
}

$backUrl = $this->url('town', array(
	'longitude' => $this->longitude,
	'latitude' => $this->latitude
));

?>

<br><br><a href='<?php echo $backUrl; ?>'>Tilbake til landsby</a>