<h2>Bygningstre</h2>

<div class='buildingTree'>

<?php

if(!$this->uncompletedBuilding) {
	$formUrl = $this->url('town', array(
		'controller' => 'index',
		'action' => 'startbuild',
		'longitude' => $this->longitude,
		'latitude' => $this->latitude
	));
	echo "<form action='" . $formUrl . "' method='POST'>";
}

foreach($this->buildings as $building) {
	if(in_array($building, $this->completedBuildings)) {
		$isCompleted = true;
	} else {
		$isCompleted = false;
	}
	
	echo "<div class='building " . str_replace(' ', '_', $building) . " ";
	
	if($isCompleted) {
		echo 'completed';
	} else if($building == $this->uncompletedBuilding->type) {
		echo 'inProgress';
	} else {
		echo 'notStarted';
	}
	
	echo "'>" . ucfirst($building);
	
	if(!$this->uncompletedBuilding && !$isCompleted && in_array($building, $this->buildingsWithPrerequisitesObtained)) {
		echo "<br /><input type='radio' name='buildingToStart' value='" . $building . "'>";
	}
	
	echo "</div>\n";
}

if(!$this->uncompletedBuilding) {
	echo "<input type='submit' id='startBuildingSubmit' value='Start bygging'>";
	
	echo "</form>";
}

?>

</div>

<?php

$backUrl = $this->url('town', array(
	'longitude' => $this->longitude,
	'latitude' => $this->latitude
));

?>

<a href='<?php echo $backUrl; ?>'>Tilbake til landsby</a>