<h2>Map</h2>

<table class="mapTable"><tr>

<?php

$lastLongitude = 0;
foreach($this->mapSquares as $square) {
	if($square->longitude != $lastLongitude) {
		// Insert new table row
		echo "</tr><tr>";
	}
	echo "<td class='" ;
	switch($square->type) {
		case 0:
			echo "plains";
			break;
		case 1:
			echo "water";
			break;
		case 2:
			echo "forest";
			break;
		case 3:
			echo "stone";
			break;
		case 4:
			echo "gold";
			break;
	}
	echo "'>&nbsp;</td>\n";
	$lastLongitude = $square->longitude;
}

?>

</tr></table>