<h2>Landsby - Stopp bygningsprosjekt</h2>

Dersom du avslutter bygningsprosjektet nå vil alt arbeid og alle resurser brukt til byggingen av det nåværende bygningsprosjektet gå tapt.<br />
Er du sikker på at du ønsker å stoppe bygningsprosjektet?<br /><br />

<?php

$formUrl = $this->url('game', array(
	'controller' => 'town',
	'action' => 'stopbuild',
	'longitude' => $this->longitude,
	'latitude' => $this->latitude
));

?>

<form action='<?php echo $formUrl; ?>' method='POST'>
	<input type='submit' name='stopBuild' value='No'>
	<input type='submit' name='stopBuild' value='Yes'>
</form>