<h2>Kart</h2>

<?php

// Print eventual message
if(isset($this->message)) {
	echo "<div class='message'>" . $this->message . "</div>";
}

// Print eventual travel notice
if($this->playerIsTraveling) {
	echo "<div class='notice'>" . $this->travelNotice . "</div>";
}

?>

<table class="mapTable">
<tr>
<td rowspan="<?php echo ($this->mapHeight + 2); ?>" class="navigation">
<a href="<?php echo $this->url('game', array(
						'controller' => 'map',
						'action' => 'index',
						'longitude' => $this->centerLongitude,
						'latitude' => $this->centerLatitude - 1)); ?>">Vest</a>
</td>
<td colspan="<?php echo $this->mapWidth; ?>" class="navigation">
<a href="<?php echo $this->url('game', array(
						'controller' => 'map',
						'action' => 'index',
						'longitude' => $this->centerLongitude - 1,
						'latitude' => $this->centerLatitude)); ?>">Nord</a>
</td>
<td rowspan="<?php echo ($this->mapHeight + 2); ?>" class="navigation">
<a href="<?php echo $this->url('game', array(
						'controller' => 'map',
						'action' => 'index',
						'longitude' => $this->centerLongitude,
						'latitude' => $this->centerLatitude + 1)); ?>">Øst</a>
</td>
</tr>

<?php

$lastLongitude = 0;
foreach($this->mapSquares as $square) {
	if($square->longitude != $lastLongitude) {
		// Insert new table row
		echo "</tr><tr>";
	}
	
	echo "<td class='" . $square->type;
	if($square->owner == $this->playerID) {
		echo " playerOwned";
	}
	echo "'>";
	
	$playerAtSquare = false;
	if($this->playerLongitude == $square->longitude &&
	   $this->playerLatitude == $square->latitude) {
		$playerAtSquare = true;
	}
	
	$otherPlayersAtSquare = false;
	for($i = 0; $i < count($this->players); $i++) {
		if($this->players[$i]['longitude'] == $square->longitude &&
		   $this->players[$i]['latitude'] == $square->latitude &&
		   $this->players[$i]['playerID'] != $this->playerID) {
			$otherPlayersAtSquare = true;
			break;
		}
	}
	if($playerAtSquare) {
		$class = '';
		if($this->playerIsTraveling) {
			$class = "class='traveling'";
		} else {
			$mapSquareUrl = $this->url('game', array(
					'controller' => 'map',
					'action' => 'square'
			));
				
			echo "<a class='changePosition' href='$mapSquareUrl'>";
		}
		if(! $otherPlayersAtSquare) {
			// Print player image
			echo "<img $class src='" . $this->basePath() . "/images/map/player.png" . "' />";
		} else {
			// Print double player image
			echo "<img $class src='" . $this->basePath() . "/images/map/player_both.png" . "' />";
		}
		if(! $this->playerIsTraveling) {
			echo "</a>";
		}
	} else {
		if($this->moveToSquare &&
		   $this->centerLongitude == $square->longitude &&
		   $this->centerLatitude == $square->latitude) {
			// Make "move to this position" anchor
			echo "<a class='changePosition faded' href='";
			echo $this->url('game', array(
					'controller' => 'map',
					'action' => 'moveplayer',
					'longitude' => $square->longitude,
					'latitude' => $square->latitude));
			echo "'>";
			if($otherPlayersAtSquare) {
				// Print player enemy image
				echo "<img src='" . $this->basePath() . "/images/map/player_both.png" . "' />";
			} else {
				// Print player image
				echo "<img src='" . $this->basePath() . "/images/map/player.png" . "' />";
			}
			echo "</a>";
		} else {
			if(! $this->playerIsTraveling) {
				// Make "ask me about moving to this position" anchor
				echo "<a class='changePosition' href='";
				echo $this->url('game', array(
						'controller' => 'map',
						'action' => 'move',
						'longitude' => $square->longitude,
						'latitude' => $square->latitude));
				echo "'>";
				if($otherPlayersAtSquare) {
					// Print player enemy image
					echo "<img src='" . $this->basePath() . "/images/map/player_enemy.png" . "' />";
				}
				echo "</a>";
			} else {
				if($otherPlayersAtSquare) {
					// Print player enemy image
					echo "<img src='" . $this->basePath() . "/images/map/player_enemy.png" . "' />";
				}
			}
		}
	}
	echo "</td>\n";
	$lastLongitude = $square->longitude;
}

?>

<tr>
<td colspan="<?php echo $this->mapWidth; ?>" class="navigation">
<a href="<?php echo $this->url('game', array(
						'controller' => 'map',
						'action' => 'index',
						'longitude' => $this->centerLongitude + 1,
						'latitude' => $this->centerLatitude)); ?>">Sør</a>
</td>
</tr>

</table>


<br />

<a href="<?php echo $this->url('game', array(
						'controller' => 'map',
						'action' => 'buysquare',
						'longitude' => $this->playerLongitude,
						'latitude' => $this->playerLatitude)); ?>">Kjøp rute</a>

<br />

<a href="<?php echo $this->url('game', array(
						'controller' => 'map',
						'action' => 'establishtown',
						'longitude' => $this->playerLongitude,
						'latitude' => $this->playerLatitude)); ?>">Opprett landsby</a>