<h2>Map</h2>

<table class="mapTable">
<tr>
<td rowspan="<?php echo ($this->mapHeight + 2); ?>" class="navigation">
<a href="<?php echo $this->url('game', array(
						'controller' => 'map',
						'action' => 'index',
						'longitude' => $this->longitude,
						'latitude' => $this->latitude - 1)); ?>">Venstre</a>
</td>
<td colspan="<?php echo $this->mapWidth; ?>" class="navigation">
<a href="<?php echo $this->url('game', array(
						'controller' => 'map',
						'action' => 'index',
						'longitude' => $this->longitude - 1,
						'latitude' => $this->latitude)); ?>">Opp</a>
</td>
<td rowspan="<?php echo ($this->mapHeight + 2); ?>" class="navigation">
<a href="<?php echo $this->url('game', array(
						'controller' => 'map',
						'action' => 'index',
						'longitude' => $this->longitude,
						'latitude' => $this->latitude + 1)); ?>">Høyre</a>
</td>
</tr>

<?php

$lastLongitude = 0;
foreach($this->mapSquares as $square) {
	if($square->longitude != $lastLongitude) {
		// Insert new table row
		echo "</tr><tr>";
	}
	echo "<td class='" . $square->type . "'>";
	$isPlayerAtCurrentPosition = false;
	for($i = 0; $i < count($this->players); $i++) {
		if($this->players[$i]['longitude'] == $square->longitude &&
		   $this->players[$i]['latitude'] == $square->latitude) {
			$isPlayerAtCurrentPosition = true;
			break;
		}
	}
	if($isPlayerAtCurrentPosition) {
		// Print player image
		echo "<img src='" . $this->basePath() . "/images/map/player.png" . "' />";
	} else {
		// Make "move to this position" anchor
		echo "<a class='changePosition' href='";
		echo $this->url('game', array(
						'controller' => 'map',
						'action' => 'moveplayer',
						'longitude' => $square->longitude,
						'latitude' => $square->latitude));
		echo "'></a>";
	}
	echo "</td>\n";
	$lastLongitude = $square->longitude;
}

?>

<tr>
<td colspan="<?php echo $this->mapWidth; ?>" class="navigation">
<a href="<?php echo $this->url('game', array(
						'controller' => 'map',
						'action' => 'index',
						'longitude' => $this->longitude + 1,
						'latitude' => $this->latitude)); ?>">Ned</a>
</td>
</tr>

</table>

<br />

<a href="<?php echo $this->url('game', array(
						'controller' => 'mapsquare',
						'action' => 'index')); ?>">Gå til rute</a>